---
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: git://github.com/adrienverge/yamllint
    rev: master
    hooks:
      - id: yamllint
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        exclude: "\\.zsh$"
  - repo: git://github.com/Kuniwak/vint
    rev: master
    hooks:
      - id: vint
